<li class="item clearfix"><a href="[field:arcurl/]" title="[field:fulltitle/]"><img class="fl"
                                src="[field:litpic/]" alt="[field:fulltitle/]">
                            <div class="time fr"><span class="day">[field:pubdate
                                    function="MyDate('m-d',@me)"/]</span><span class="year">[field:pubdate
                                    function="MyDate('Y',@me)"/]</span></div>
                            <h3>[field:fulltitle/]</h3>
                            <div class="txt">[field:infos/]...</div>
                        </a></li>