<?php
$z[0]=Array("arcurl","",36,51);
$z[0][4]=array();
$z[1]=Array("fulltitle","",60,78);
$z[1][4]=array();
$z[2]=Array("litpic","",105,120);
$z[2][4]=array();
$z[3]=Array("fulltitle","",127,145);
$z[3][4]=array();
$z[4]=Array("fulltitle","",171,189);
$z[4][4]=array();
$z[5]=Array("infos","",204,218);
$z[5][4]=array();
$z[6]=Array("pubdate","",264,311);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y-m-d',@me)";

?>