
<m:item name='德得模块' link='mda_main.php' rank='plus_广告管理' target='main'/>
<m:item name='广告管理' link='mda_main.php?dopost=place' rank='plus_广告管理' target='main'/>
<m:item name='查看报表' link='mda_main.php?dopost=report' rank='plus_广告管理' target='main'/>
<m:item name='结算中心' link='mda_main.php?dopost=account' rank='plus_广告管理' target='main'/>
<m:item name='德得设置' link='mda_main.php?dopost=setting' rank='plus_广告管理' target='main'/>
