
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:wx itemname="微信" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:wx>

<field:sub itemname="科目" autofield="1" type="select" isnull="true" default="Java,web前端,全栈工程师,Python,大数据,区块链,软件测试"  maxlength="250" page="">
</field:sub>
