<?php
$z[0]=Array("top","\r\n  <m:item name='上传新文件' link='media_add.php' rank='' target='main' ",12,196);
$z[0][4]=array();
$z[0][4]['item']="1_";
$z[0][4]['name']="附件管理";
$z[0][4]['display']="none";
$z[0][4]['rank']="sys_Upload,sys_MyUpload,plus_文件管理器";
$z[1]=Array("item","",200,303);
$z[1][4]=array();
$z[1][4]['name']="附件数据管理";
$z[1][4]['link']="media_main.php";
$z[1][4]['rank']="sys_Upload,sys_MyUpload";
$z[1][4]['target']="main";
$z[2]=Array("item","",307,426);
$z[2][4]=array();
$z[2][4]['name']="文件式管理器";
$z[2][4]['link']="media_main.php?dopost=filemanager";
$z[2][4]['rank']="plus_文件管理器";
$z[2][4]['target']="main";

?>